server:
  port: 8080

spring:
  application:
    name: jamcast-api

# API Configuration
api:
  openweathermap:
    base-url: https://api.openweathermap.org/data/2.5/weather
    api-key: YOUR_OPENWEATHERMAP_API_KEY  # Replace with your actual API key
  
  spotify:
    base-url: https://api.spotify.com/v1
    access-token: YOUR_SPOTIFY_ACCESS_TOKEN  # Replace with your actual access token

# Logging configuration
logging:
  level:
    com.jamcast: DEBUG
    org.springframework.web: INFO 